# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x04\x62ook\"3\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"*\n\x0e\x41\x64\x64\x42ookRequest\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\"\"\n\x0f\x41\x64\x64\x42ookResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x0b\x42ookService\x12\x36\n\x07\x41\x64\x64\x42ook\x12\x14.book.AddBookRequest\x1a\x15.book.AddBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOK']._serialized_start=21
  _globals['_BOOK']._serialized_end=72
  _globals['_ADDBOOKREQUEST']._serialized_start=74
  _globals['_ADDBOOKREQUEST']._serialized_end=116
  _globals['_ADDBOOKRESPONSE']._serialized_start=118
  _globals['_ADDBOOKRESPONSE']._serialized_end=152
  _globals['_BOOKSERVICE']._serialized_start=154
  _globals['_BOOKSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
